spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/XIAOLI
    username: postgres
    password: P@ssw0rd
    driver-class-name: org.postgresql.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xiaoli.providerone.entity

xiaoli: AAASSSDDD